apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-application
  labels:
    app: nginx
spec:
  selector:
    matchLabels:
      app: nginx
  replicas: 7
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginxapplication
        image: httpd
        ports:
        - containerPort: 80